ITEM.name = "Боевая модель костюма с замкнутым дыханием"
ITEM.model = Model("models/tnb/items/shirt_rebelbag.mdl")
ITEM.width = 2
ITEM.height = 2
ITEM.weight = 16
ITEM.description = "Имеет хорошие защитные свойства, может защищать от снайперских выстрелов, удобная модульная конструкция. В основе жилета – керамико-композитные бронепанели, обладающие высокой прочностью при небольшой массе. Штурмовая комплектация дополняется защитой паховых и боковых зон, также в комплект защиты входят одежда из баллистической армидной ткани, противогаз военного назначения, наколенники и налокотники."
ITEM.price = 25
ITEM.noBusiness = true
ITEM.outfitCategory = "suit"
ITEM.IsArmor = true
ITEM.protectProcent = 35
ITEM.standartDurability = 100
ITEM.modelEquipFem = Model("models/player/hazmat/hazmat1980_npc.mdl")
ITEM.modelEquipMal = Model("models/player/hazmat/hazmat1980_npc.mdl")
ITEM.protectgas = true
ITEM.iconCam = {
	pos = Vector(0, -3, 200),
	ang = Angle(90, 90, 0),
	fov = 7.5
}