ITEM.name = "Кейс для магазина"
ITEM.description = "Футляр для хранения различных оружейных магазинов, облегчающий транспортировку."
ITEM.model = Model("models/illusion/eftcontainers/magbox.mdl")
ITEM.width = 3
ITEM.height = 2
ITEM.weight = 2
ITEM.invWidth = 4
ITEM.invHeight = 3
ITEM.canEquip = false
ITEM.bDropOnDeath = true