ITEM.name = "Денежный кейс"
ITEM.description = "Футляр для хранения больших сумм денег или редких ценностей, усиленный и бронированный для обеспечения его безопасности при транспортировке."
ITEM.model = Model("models/illusion/eftcontainers/moneycase.mdl")
ITEM.width = 3
ITEM.height = 2
ITEM.weight = 1.8
ITEM.invWidth = 3
ITEM.invHeight = 3
ITEM.canEquip = false
ITEM.bDropOnDeath = true