ITEM.name = "Патроны для винтовок"
ITEM.model = "models/Items/BoxMRounds.mdl"
ITEM.ammo = "ar2" 
ITEM.ammoAmount = 30 
ITEM.description = "Коробка, содержащая %s патроны для винтовки."
ITEM.category = "Боеприпасы"
ITEM.price = 18
ITEM.bDropOnDeath = true
ITEM.weight = 0.4